name: apexive
description: Apexive Sample Code for Review

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^5.0.0
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
